/**
 * Reads core and config versions from their workspace package.json files and
 * writes src/generated-versions.ts. Runs as part of prepack so the published
 * CLI always stamps the correct npm versions into scaffolded projects.
 *
 * Never edit src/generated-versions.ts manually — it is overwritten on every build.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '../../..');

function readVersion(pkgPath: string): string {
  return JSON.parse(readFileSync(pkgPath, 'utf8')).version as string;
}

const coreVersion = readVersion(join(root, 'packages/core/package.json'));
const configVersion = readVersion(join(root, 'packages/config/package.json'));

const output = `// Auto-generated by scripts/generate-versions.ts — do not edit manually.
// Re-generated on every prepack from packages/core and packages/config package.json.
export const CORE_VERSION = '^${coreVersion}';
export const CONFIG_VERSION = '^${configVersion}';
`;

writeFileSync(join(here, '../src/generated-versions.ts'), output, 'utf8');
console.log(`[generate-versions] core=${coreVersion} config=${configVersion}`);
